# ============================================================================================
# capture_usb_ila.tcl -- drive the USB spike ILA from Vivado's Hardware Manager.
#
#     source tools/vivado_scripts/capture_usb_ila.tcl
#     usb_probes                 ;# list the probes actually present, with their real names
#     usb_arm_activity           ;# capture 1: first line activity, full rate -- the signal-quality one
#     usb_arm_connect            ;# capture 2: the moment the core decides a device is connected
#     usb_arm_error              ;# capture 3: conerr asserting, with pre-trigger history
#     usb_run                    ;# arm (non-blocking), then plug the device in
#     usb_status                 ;# has it triggered?
#     usb_fetch <tag>            ;# upload + waveform + CSV
#
# Reading the waveform (see add_usb_ila.tcl for the packing):
#   usb_p1_lines / usb_p0_lines : bit4 dp_in, bit3 dm_in, bit2 oe, bit1 dp_out, bit0 dm_out
#   usb_p1_dbg  / usb_p0_dbg    : bit18 connected, bits17:14 state, bits13:0 pc (microprogram counter)
#   usb_status                  : bit7:6 p1_typ, bit5 p1_report, bit4 p1_conerr,
#                                 bit3:2 p0_typ, bit1 p0_report, bit0 p0_conerr
#
# typ: 0 = no device, 1 = keyboard, 2 = mouse, 3 = gamepad.
#
# IDLE POLARITY IS THE THING TO LOOK AT FIRST. A full-speed device idles J = D+ HIGH, D- low.
# A low-speed device idles the other way round. So with a device plugged in and nothing happening,
# dp_in=1 / dm_in=0 means it attached as full speed, and dp_in=0 / dm_in=1 means low speed. That
# single observation tells you whether the device is even offering the speed you are testing.
# ============================================================================================

proc _uila {} {
    set ilas [get_hw_ilas -quiet]
    if {[llength $ilas] == 0} {
        error "No ILA found. Is the DEBUG_USB_ILA bitstream programmed, and refresh_hw_device run\
               with the matching .ltx? Remember the .ltx is regenerated by every implementation run."
    }
    return [lindex $ilas 0]
}

# Never hardcode probe names -- Vivado's naming depends on how the generate blocks flatten.
proc _up {frag} {
    set hits [get_hw_probes -quiet -of_objects [_uila] -filter "NAME =~ *${frag}*"]
    if {[llength $hits] == 0} { error "No probe matching '*${frag}*'. Run usb_probes to see what exists." }
    if {[llength $hits] > 1}  { puts "WARNING: '$frag' matched [llength $hits] probes, using [lindex $hits 0]" }
    return [lindex $hits 0]
}

proc usb_probes {} {
    foreach p [get_hw_probes -of_objects [_uila]] {
        puts [format "  %-60s width %s" [get_property NAME $p] [get_property WIDTH $p]]
    }
}

proc _udc {p} {
    set w [get_property WIDTH $p]
    return "eq${w}'b[string repeat X $w]"
}

proc _ureset {} {
    set ila [_uila]
    set_property CONTROL.DATA_DEPTH 4096 $ila
    set_property CONTROL.TRIGGER_CONDITION AND $ila
    set_property CONTROL.CAPTURE_MODE ALWAYS $ila
    foreach p [get_hw_probes -of_objects $ila] {
        catch { set_property TRIGGER_COMPARE_VALUE [_udc $p] $p }
        catch { set_property CAPTURE_COMPARE_VALUE [_udc $p] $p }
    }
}

# ---- capture 1: first line activity, at full rate -- THE SIGNAL-QUALITY CAPTURE ----------------
# Trigger the moment port 1's D+ leaves the full-speed idle (J) state, i.e. dp_in goes low, and
# store every 96MHz tick. 4096 samples = 42.7us, and a full-speed bit is 8 samples, so this covers
# roughly 512 bit times of real traffic at maximum detail.
#
# This is the capture that answers the actual hardware question: with no series resistors on D+/D-,
# are the J/K transitions clean, or is there ringing and reflection? Look for transitions that take
# more than a sample or two to settle, or bits sampled inconsistently at the 8x points.
# Trigger position is late in the buffer so a good chunk of the idle line before the first packet is
# captured too -- a noisy idle is just as informative as a noisy edge.
proc usb_arm_activity {} {
    set ila [_uila]
    _ureset
    set_property TRIGGER_COMPARE_VALUE eq5'b0XXXX [_up usb_p1_lines]
    set_property CONTROL.CAPTURE_MODE ALWAYS $ila
    set_property CONTROL.TRIGGER_POSITION 512 $ila
    puts "Armed: trigger on port1 D+ going low (leaving full-speed idle), full rate, 42.7us window."
    puts "If this never fires, check the idle polarity first -- a low-speed device idles D+ LOW,"
    puts "so it would already be sitting in the trigger condition rather than entering it."
}

# ---- capture 2: connection detected ------------------------------------------------------------
# The core sets `connected` once it believes a device is attached. Triggering on the transition
# shows the attach sequence and the start of the enumeration microprogram that follows.
proc usb_arm_connect {} {
    set ila [_uila]
    _ureset
    set_property TRIGGER_COMPARE_VALUE eq19'b1XXXXXXXXXXXXXXXXXX [_up usb_p1_dbg]
    set_property CONTROL.CAPTURE_MODE ALWAYS $ila
    set_property CONTROL.TRIGGER_POSITION 256 $ila
    puts "Armed: trigger on port1 connected=1, full rate."
}

# ---- capture 3: protocol error, with history ---------------------------------------------------
# conerr means the core gave up. Trigger position mid-buffer so the traffic LEADING UP to the
# failure is captured, which is the part that says why -- and note the pc value at the failure,
# since that pinpoints where in the enumeration ROM it died.
proc usb_arm_error {} {
    set ila [_uila]
    _ureset
    set_property TRIGGER_COMPARE_VALUE eq8'bXXX1XXXX [_up usb_status]
    set_property CONTROL.CAPTURE_MODE ALWAYS $ila
    set_property CONTROL.TRIGGER_POSITION 2048 $ila
    puts "Armed: trigger on port1 conerr, mid-buffer so the run-up to the failure is captured."
}

# ---- run / status / fetch ----------------------------------------------------------------------
# Status lives under STATUS.*, and -update_hw_probes false matters: a full refresh re-reads the
# probes file and can knock the core out of its armed state, which looks exactly like a trigger
# that never fired.
proc usb_status {} {
    set ila [_uila]
    refresh_hw_device -update_hw_probes false -quiet [current_hw_device]
    puts [format "  %-16s %s" CORE_STATUS  [get_property STATUS.CORE_STATUS  $ila]]
    puts [format "  %-16s %s" SAMPLE_COUNT [get_property STATUS.SAMPLE_COUNT $ila]]
    return [get_property STATUS.CORE_STATUS $ila]
}

# Non-blocking arm, so the console stays usable while you plug the device in. wait_on_hw_ila would
# block Vivado entirely, and you need your hands free here.
proc usb_run {} {
    run_hw_ila [_uila]
    set st [usb_status]
    if {$st eq "IDLE"} {
        error "Core still IDLE after run_hw_ila -- it did NOT arm. Do not plug anything in yet."
    }
    puts "Armed. NOW plug the USB device into the port you are testing."
    puts "Then: usb_status, and usb_fetch <tag> once it has triggered."
}

# Refuses to upload an untriggered core: doing so STOPS it and throws the capture away
# ("[Labtools 27-157] hw_ila stopped. No data to upload.").
proc usb_fetch {{tag usb}} {
    set st [usb_status]
    if {[string match -nocase "*WAITING*" $st] || $st eq "IDLE"} {
        error "Core is '$st' -- NOT triggered. Uploading now would stop it and discard the capture."
    }
    set d [upload_hw_ila_data [_uila]]
    display_hw_ila_data $d
    set csv [file normalize "C:/Users/wottle/Documents/Development/LisaFPGA/ila_${tag}.csv"]
    write_hw_ila_data -csv_file $csv -force $d
    puts "CSV written to: $csv"
}

puts "Loaded. Arm: usb_arm_activity | usb_arm_connect | usb_arm_error"
puts "       Run: usb_run -> (plug device in) -> usb_status -> usb_fetch <tag>"
