# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/wottle/Documents/Development/LisaFPGA/LisaFPGA.srcs/sources_1/ip/clock_divider/clock_divider.xci
# IP: The module: 'clock_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wottle/Documents/Development/LisaFPGA/LisaFPGA.gen/sources_1/ip/clock_divider/clock_divider_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_divider'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/wottle/Documents/Development/LisaFPGA/LisaFPGA.gen/sources_1/ip/clock_divider/clock_divider.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/wottle/Documents/Development/LisaFPGA/LisaFPGA.gen/sources_1/ip/clock_divider/clock_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/wottle/Documents/Development/LisaFPGA/LisaFPGA.srcs/sources_1/ip/clock_divider/clock_divider.xci
# IP: The module: 'clock_divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wottle/Documents/Development/LisaFPGA/LisaFPGA.gen/sources_1/ip/clock_divider/clock_divider_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/wottle/Documents/Development/LisaFPGA/LisaFPGA.gen/sources_1/ip/clock_divider/clock_divider.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/wottle/Documents/Development/LisaFPGA/LisaFPGA.gen/sources_1/ip/clock_divider/clock_divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
